name: Build and Test

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build on Node.js ${{ matrix.node-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Upload build artifacts
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '18.x'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  integration-test:
    runs-on: ubuntu-latest
    needs: build-and-test
    services:
      nacos:
        image: nacos/nacos-server:v2.3.0
        ports:
          - 8848:8848
        env:
          MODE: standalone
          PREFER_HOST_MODE: hostname
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Wait for Nacos to be ready
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:8848/nacos/v1/console/health/readiness; do sleep 2; done'

      - name: Run integration tests
        run: npm run test
        env:
          NACOS_SERVER_ADDR: localhost:8848
          NACOS_USERNAME: nacos
          NACOS_PASSWORD: nacos